### ISSUE TITLE
Bug: Current config.json.tpl does not get applied via terraform

### ISSUE THREAD

**Issue by kulla** [serlo/infrastructure-modules-shared#21]
Currently we have `sync.interval` set to `6` in the file `config.json.tpl` (see https://github.com/serlo/infrastructure-modules-shared/blob/main/enmeshed/config.json.tpl#L22). However, when I have a look at `/config.json` in the enmeshed container via `kubectl exec <pod-name>  -n data-wallet -i -t -- sh` there is the old number `60` stored.

**Comment by hugotiburtino** [comment]
Using subPath the volume is not updated automatically. https://kubernetes.io/docs/concepts/configuration/secret/#mounted-secrets-are-updated-automatically
Anyways, I've deleted the old pod and the new one comes with the applied value. Please check if the behavior corresponds to the desired.

**Comment by inyono** [comment]
Typical workaround for such cases: add a checksum of the config as an environment variable to the pod. Since changes in environment variables will trigger a redeployment, this ensures that config updates are handled correctly. See e.g. https://github.com/serlo/infrastructure-modules-serlo.org/blob/main/server/main.tf#L78-L81.
